# Generated by Django 4.2.20 on 2025-03-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Пусто', max_length=50, verbose_name='Название')),
                ('anons', models.CharField(default='Пусто', max_length=250, verbose_name='Анонс')),
                ('full_text', models.TextField(default=' ', verbose_name='Статья')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
